name: myapp
description: "A new Flutter project."

# Prevent publishing this package to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

# Set minimum required Flutter SDK version
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  flutter_tts: 3.8.5         
  shared_preferences: 2.2.2
  speech_to_text: ^6.3.0
  record: ^4.4.4
  camera: ^0.10.5+5
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules from the Flutter team
  flutter_lints: ^5.0.0

flutter:
  # Enables use of Material Icons
  uses-material-design: true

  # Add assets here if needed
  # assets:
  #   - images/logo.png
  #   - sounds/notification.mp3

  # Add custom fonts here if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
